services:
  db:
    ports:
      - 5432:5432
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_DB: ${POSTGRES_DB:-alerts}
    container_name: alerts-db
    restart: always
    #volumes:
    #  - /data/postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
