services:
  app:
    build: .
    image: ${IMAGE_NAME:-tg-alert}
    container_name: tg-alert-app
    restart: always
    environment:
      TELEGRAM_TOKEN:
      DOMAIN:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_DB: ${POSTGRES_DB:-alerts}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_DB: ${POSTGRES_DB:-alerts}
    container_name: tg-alert-db
    restart: always
    ports:
      - 5432:5432
    #volumes:
    #  - /data/postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
